### ISSUE TITLE
Shiny card seems not to be generated randomly

### ISSUE THREAD

**Issue by ketelsb** [TreasureIslandMC/TradingCards#24]
**Describe the bug**
Grind the cards for hours and you find that when a shiny card drops, it is always the same shiny card.
After a while (server reboot?) the Shiny Card changes to a different card. But then it always drops that card

**To Reproduce**
1. Grind mobs
2. Collect cards
3. After a while you get shinies
4. When you are given a shiny, it is always the same shiny

**Expected behavior**
When i'm given a shiny card, it should be a random card and not the same every time

**Error Logs**
Paste any errors here.
**Screenshots**

**Server & Plugin Versions:**
 - Server Version:
 - Minecraft:
 - XenTradingCards:

**Comment by sarhatabaot** [comment]
Fixed in PR #25.
